# Generated by Django 6.0.1 on 2026-02-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='ip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
