# Generated by Django 5.2.11 on 2026-02-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_rental', '0002_alter_requestlog_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivationalQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(blank=True, help_text='Optional motivational quote text', null=True)),
                ('author', models.CharField(default='Unknown', help_text='Author of the quote', max_length=200)),
                ('image', models.ImageField(help_text='Image for the quote (required)', upload_to='quotes/')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this quote is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
