# Generated by Django 5.2.11 on 2026-03-03 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_rental', '0005_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='recharge',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recharges', to='water_rental.payment'),
        ),
    ]
