# Generated by Django 5.2.11 on 2026-03-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_rental', '0006_recharge_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recharge',
            name='litres_purchased',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recharge',
            name='paisa_per_litre_at_purchase',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
