# Generated by Django 6.0 on 2025-12-18 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_rental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('device_chip_id', models.CharField(max_length=100, unique=True)),
                ('device_status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=20)),
                ('last_recharge_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recharge_date', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('payment_status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='water_rental.customer')),
            ],
            options={
                'ordering': ['-recharge_date'],
            },
        ),
        migrations.CreateModel(
            name='Recharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recharge_date', models.DateTimeField(auto_now_add=True)),
                ('litres_allocated', models.FloatField(default=500)),
                ('litres_used', models.FloatField(default=0)),
                ('litres_remaining', models.FloatField(default=500)),
                ('expiry_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('expired', 'Expired')], default='active', max_length=20)),
                ('needs_filtration', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharges', to='water_rental.customer')),
            ],
            options={
                'ordering': ['-recharge_date'],
            },
        ),
        migrations.CreateModel(
            name='WaterUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_date', models.DateField(auto_now_add=True)),
                ('last_24hr_usage', models.FloatField(default=0)),
                ('monthly_usage', models.FloatField(default=0)),
                ('per_day_average', models.FloatField(default=0)),
                ('current_day_usage', models.FloatField(default=0)),
                ('thirty_day_usage', models.FloatField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_usages', to='water_rental.customer')),
            ],
            options={
                'ordering': ['-usage_date'],
                'unique_together': {('customer', 'usage_date')},
            },
        ),
    ]
