# Generated by Django 6.0 on 2025-12-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_rental', '0002_customer_payment_recharge_waterusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterqualityreading',
            name='tds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterqualityreading',
            name='water_quality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
