# Generated by Django 6.0 on 2025-12-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_rental', '0003_customer_latitude_customer_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='block_unblock',
            field=models.BooleanField(default=True),
        ),
    ]
