# Generated by Django 5.2.6 on 2025-12-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_rental', '0008_dismissedalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterusage',
            name='usage_date',
            field=models.DateField(),
        ),
    ]
