# Generated by Django 5.2.6 on 2025-12-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_rental', '0009_alter_waterusage_usage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='future_field1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='future_field2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='future_field3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='future_field4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='future_field5',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='future_field6',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contaminanttest',
            name='future_field1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contaminanttest',
            name='future_field2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contaminanttest',
            name='future_field3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contaminanttest',
            name='future_field4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contaminanttest',
            name='future_field5',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contaminanttest',
            name='future_field6',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='future_field1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='future_field2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='future_field3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='future_field4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='future_field5',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='future_field6',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dismissedalert',
            name='future_field1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dismissedalert',
            name='future_field2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dismissedalert',
            name='future_field3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dismissedalert',
            name='future_field4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dismissedalert',
            name='future_field5',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dismissedalert',
            name='future_field6',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='future_field1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='future_field2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='future_field3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='future_field4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='future_field5',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='future_field6',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recharge',
            name='future_field1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recharge',
            name='future_field2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recharge',
            name='future_field3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recharge',
            name='future_field4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recharge',
            name='future_field5',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recharge',
            name='future_field6',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='future_field1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='future_field2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='future_field3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='future_field4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='future_field5',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='future_field6',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterqualityreading',
            name='future_field1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='waterqualityreading',
            name='future_field2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='waterqualityreading',
            name='future_field3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterqualityreading',
            name='future_field4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterqualityreading',
            name='future_field5',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterqualityreading',
            name='future_field6',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watersource',
            name='future_field1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='watersource',
            name='future_field2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='watersource',
            name='future_field3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watersource',
            name='future_field4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watersource',
            name='future_field5',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watersource',
            name='future_field6',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterusage',
            name='future_field1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='waterusage',
            name='future_field2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='waterusage',
            name='future_field3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterusage',
            name='future_field4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterusage',
            name='future_field5',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterusage',
            name='future_field6',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
