# Generated by Django 4.2.27 on 2025-12-25 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('water_rental', '0010_alert_future_field1_alert_future_field2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('main_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('days', models.IntegerField()),
                ('litres_allocated', models.IntegerField(default=0)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('future_field1', models.CharField(blank=True, max_length=255, null=True)),
                ('future_field2', models.CharField(blank=True, max_length=255, null=True)),
                ('future_field3', models.TextField(blank=True, null=True)),
                ('future_field4', models.FloatField(blank=True, null=True)),
                ('future_field5', models.DateTimeField(blank=True, null=True)),
                ('future_field6', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['days'],
            },
        ),
        migrations.CreateModel(
            name='UserComplain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=20)),
                ('device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('problem_statement', models.TextField()),
                ('complain_date', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('assigned_person_details', models.TextField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('pending', 'Pending')], default='open', max_length=20)),
                ('future_field1', models.CharField(blank=True, max_length=255, null=True)),
                ('future_field2', models.CharField(blank=True, max_length=255, null=True)),
                ('future_field3', models.TextField(blank=True, null=True)),
                ('future_field4', models.FloatField(blank=True, null=True)),
                ('future_field5', models.DateTimeField(blank=True, null=True)),
                ('future_field6', models.JSONField(blank=True, null=True)),
                ('assigned_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complains', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complains', to='water_rental.customer')),
            ],
            options={
                'verbose_name': 'User Complain',
                'verbose_name_plural': 'User Complains',
                'ordering': ['-complain_date'],
            },
        ),
    ]
