# Generated by Django 4.2.27 on 2025-12-25 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('water_rental', '0011_adminplan_usercomplain'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='current_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='water_rental.adminplan'),
        ),
    ]
