# Generated by Django 4.2.27 on 2025-12-25 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('water_rental', '0012_customer_current_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('coupon_type', models.CharField(choices=[('percentage', 'Percentage Discount'), ('fixed', 'Fixed Amount'), ('free_litres', 'Free Litres')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=20)),
                ('max_usage', models.IntegerField(blank=True, null=True)),
                ('current_usage', models.IntegerField(default=0)),
                ('max_usage_per_customer', models.IntegerField(default=1)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('future_field1', models.CharField(blank=True, max_length=255, null=True)),
                ('future_field2', models.CharField(blank=True, max_length=255, null=True)),
                ('future_field3', models.TextField(blank=True, null=True)),
                ('future_field4', models.FloatField(blank=True, null=True)),
                ('future_field5', models.DateTimeField(blank=True, null=True)),
                ('future_field6', models.JSONField(blank=True, null=True)),
                ('applicable_plans', models.ManyToManyField(blank=True, related_name='coupons', to='water_rental.adminplan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('future_field1', models.CharField(blank=True, max_length=255, null=True)),
                ('future_field2', models.CharField(blank=True, max_length=255, null=True)),
                ('future_field3', models.TextField(blank=True, null=True)),
                ('future_field4', models.FloatField(blank=True, null=True)),
                ('future_field5', models.DateTimeField(blank=True, null=True)),
                ('future_field6', models.JSONField(blank=True, null=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='water_rental.coupon')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='water_rental.customer')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_usages', to='water_rental.payment')),
            ],
            options={
                'ordering': ['-used_at'],
                'unique_together': {('coupon', 'customer', 'used_at')},
            },
        ),
    ]
