# Generated by Django 4.2.27 on 2025-12-26 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('water_rental', '0013_coupon_couponusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='number_of_family_members',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customer',
            name='ota_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='ota_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='OTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=100, unique=True)),
                ('bin_file', models.FileField(upload_to='ota_firmware/')),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('future_field1', models.CharField(blank=True, max_length=255, null=True)),
                ('future_field2', models.CharField(blank=True, max_length=255, null=True)),
                ('future_field3', models.TextField(blank=True, null=True)),
                ('future_field4', models.FloatField(blank=True, null=True)),
                ('future_field5', models.DateTimeField(blank=True, null=True)),
                ('future_field6', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ota_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
    ]
