# Generated by Django 4.2.27 on 2025-12-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_rental', '0014_customer_number_of_family_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='calibration_factor',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='customer',
            name='water_volume',
            field=models.FloatField(default=0.0),
        ),
    ]
