# Generated by Django 4.2.27 on 2025-12-26 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('water_rental', '0015_customer_calibration_factor_customer_water_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibration_factor', models.FloatField()),
                ('water_volume', models.FloatField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('extra_field1', models.CharField(blank=True, max_length=255, null=True)),
                ('extra_field2', models.CharField(blank=True, max_length=255, null=True)),
                ('future_field1', models.CharField(blank=True, max_length=255, null=True)),
                ('future_field2', models.CharField(blank=True, max_length=255, null=True)),
                ('future_field3', models.TextField(blank=True, null=True)),
                ('future_field4', models.FloatField(blank=True, null=True)),
                ('future_field5', models.DateTimeField(blank=True, null=True)),
                ('future_field6', models.JSONField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_records', to='water_rental.customer')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
